name: Build And Push to DOcker Hub
on: push
jobs:
  build-container:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Login to Azure Container Rregistry
        uses: docker/login-action@v3
        with:
          registry: optimus.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: build and push docke hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: outgazers/optimus-front:latest

    


      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username:  ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: build and push docke hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: outgazers/optimus-front:latest

    
